insert into banque(designation) values('BOA Analakeky');
insert into banque(designation) values('BFV-SG Antaninarenina');
insert into banque(designation) values('BOA Tanjombato');
insert into banque(designation) values('BFV-SG Anosizato');
insert into banque(designation) values('BOA Andoharanofotsy');
insert into banque(designation) values('BOA Antaninarenina');
insert into banque(designation) values('BFV-SG Tanjombato');
insert into banque(designation) values('BOA Fenoarivo');
insert into banque(designation) values('BFV-SG Antaninarenina');
insert into banque(designation) values('BFV-SG Andravohangy');

insert into ville(designation)values ('Analakely');
insert into ville(designation)values ('Ankadimbahoaka');
insert into ville(designation)values ('Fenoarivo');
insert into ville(designation)values ('Anosizato');
insert into ville(designation)values ('Tsampanana');
insert into ville(designation)values ('Ilafy');
insert into ville(designation)values ('Tanjombato');
insert into ville(designation)values ('Antaninarenina');
insert into ville(designation)values ('Andravohangy');
insert into ville(designation)values ('Andoharanofotsy');

insert into type_compte(designation) values('courant');
insert into type_compte(designation) values('eparne');
insert into type_compte(designation) values('paypal');

insert into type_operation(designation)values('versement');
insert into type_operation(designation)values('retrait');

insert into operation(id_compte,date_operation,montant,id_type_operation)values(1,'2017-02-02',23000,1);
insert into operation(id_compte,date_operation,montant,id_type_operation)values(2,'2017-01-02',2000,2);
insert into operation(id_compte,date_operation,montant,id_type_operation)values(3,'2017-02-01',3600,1);
insert into operation(id_compte,date_operation,montant,id_type_operation)values(4,'2017-02-02',630,2);
insert into operation(id_compte,date_operation,montant,id_type_operation)values(5,'2017-02-03',8900,1);
insert into operation(id_compte,date_operation,montant,id_type_operation)values(6,'2017-02-04',520,2);
insert into operation(id_compte,date_operation,montant,id_type_operation)values(7,'2017-02-05',4500,1);
insert into operation(id_compte,date_operation,montant,id_type_operation)values(8,'2017-02-01',23000,2);
insert into operation(id_compte,date_operation,montant,id_type_operation)values(1,'2017-02-11',6300,1);
insert into operation(id_compte,date_operation,montant,id_type_operation)values(2,'2017-01-12',2500,2);
insert into operation(id_compte,date_operation,montant,id_type_operation)values(3,'2017-02-13',2300,1);
insert into operation(id_compte,date_operation,montant,id_type_operation)values(4,'2017-02-14',2000,2);
insert into operation(id_compte,date_operation,montant,id_type_operation)values(5,'2017-02-15',8900,1);
insert into operation(id_compte,date_operation,montant,id_type_operation)values(6,'2017-02-16',3200,2);
insert into operation(id_compte,date_operation,montant,id_type_operation)values(7,'2017-02-17',5600,1);
insert into operation(id_compte,date_operation,montant,id_type_operation)values(8,'2017-02-18',5210,2);
insert into operation(id_compte,date_operation,montant,id_type_operation)values(1,'2017-01-02',1000,1);
insert into operation(id_compte,date_operation,montant,id_type_operation)values(2,'2017-01-02',2000,2);
insert into operation(id_compte,date_operation,montant,id_type_operation)values(3,'2017-01-01',3000,1);
insert into operation(id_compte,date_operation,montant,id_type_operation)values(4,'2017-01-02',1000,2);
insert into operation(id_compte,date_operation,montant,id_type_operation)values(5,'2017-01-03',3000,1);
insert into operation(id_compte,date_operation,montant,id_type_operation)values(6,'2017-01-04',5410,2);
insert into operation(id_compte,date_operation,montant,id_type_operation)values(7,'2017-01-05',2300,1);
insert into operation(id_compte,date_operation,montant,id_type_operation)values(8,'2017-01-01',4500,2);

insert into client(nom,prenom,date_naissance,adresse,mail,sexe)values('Manda','Rakotoseheno','1995-05-02','Ambohijanaka','mahefa@gmail.com','Homme');
insert into client(nom,prenom,date_naissance,adresse,mail,sexe)values('Domoina','Ramala onja fehizoro','1994-04-03','Manajary','domoin@gmail.com','Homme');
insert into client(nom,prenom,date_naissance,adresse,mail,sexe)values('Narindra','Tolotraniavo','1986-05-04','Malaza','narindra@gmail.com','Femme');
insert into client(nom,prenom,date_naissance,adresse,mail,sexe)values('Tatamo','Ramahefanimanana','1980-06-05','Tanjombato','andi@gmail.com','Homme');
insert into client(nom,prenom,date_naissance,adresse,mail,sexe)values('Andi','Fitiavana','1990-07-06','Ankadimbahoaka','tatamo@gmail.com','Femme');
insert into client(nom,prenom,date_naissance,adresse,mail,sexe)values('Ango','Nomentsoa','1983-06-07','Analakely','Fitahiana@gmail.com','Femme');
insert into client(nom,prenom,date_naissance,adresse,mail,sexe)values('Fitahiana','Rasolofomanana','1953-03-08','Ambomiadana','Manou@gmail.com','Homme');
insert into client(nom,prenom,date_naissance,adresse,mail,sexe)values('Manou','Andrimanantenasoa','1995-06-09','Ambomiadana','Ango@gmail.com','Femme');
insert into client(nom,prenom,date_naissance,adresse,mail,sexe)values('Sheillah','Ramonjisoa','1984-09-10','Antsakaviro','Sheillah@gmail.com','Homme');
insert into client(nom,prenom,date_naissance,adresse,mail,sexe)values('Lionel','Ramamonjisoa','1975-04-12','Fenoarivo','Lionel@gmail.com','Homme');
insert into client(nom,prenom,date_naissance,adresse,mail,sexe)values('Sarobidy','Rakotoson','1965-05-13','Ambohijanaka','Sarobidy@gmail.com','Femme');
insert into client(nom,prenom,date_naissance,adresse,mail,sexe)values('Tantely','Razakanrainy','1962-06-02','Ifarihy','Tantely@gmail.com','homme');
insert into client(nom,prenom,date_naissance,adresse,mail,sexe)values('Tolotra','Andrianirina','1975-08-02','Tamamtave','Tolotra@gmail.com','Femme');

insert into compte(id_operation,id_type_compte,id_agence,id_client,numero,date_creation,solde)values(1,1,1,1,125125,'2017-02-02',15000000);
insert into compte(id_operation,id_type_compte,id_agence,id_client,numero,date_creation,solde)values(2,3,2,2,125125,'2017-02-02',14000000);
insert into compte(id_operation,id_type_compte,id_agence,id_client,numero,date_creation,solde)values(3,2,3,3,125125,'2017-02-02',16000000);
insert into compte(id_operation,id_type_compte,id_agence,id_client,numero,date_creation,solde)values(4,1,4,4,125125,'2017-02-02',14000000);
insert into compte(id_operation,id_type_compte,id_agence,id_client,numero,date_creation,solde)values(5,2,5,5,125125,'2017-02-02',13000000);
insert into compte(id_operation,id_type_compte,id_agence,id_client,numero,date_creation,solde)values(6,3,6,6,125125,'2017-02-02',12000000);
insert into compte(id_operation,id_type_compte,id_agence,id_client,numero,date_creation,solde)values(7,1,7,7,125125,'2017-02-02',11000000);
insert into compte(id_operation,id_type_compte,id_agence,id_client,numero,date_creation,solde)values(8,2,8,8,125125,'2017-02-02',13000000);
insert into compte(id_operation,id_type_compte,id_agence,id_client,numero,date_creation,solde)values(9,3,9,9,125125,'2017-02-02',13000000);
insert into compte(id_operation,id_type_compte,id_agence,id_client,numero,date_creation,solde)values(10,1,1,10,125125,'2017-02-02',11000000);
insert into compte(id_operation,id_type_compte,id_agence,id_client,numero,date_creation,solde)values(1,2,2,1,125125,'2017-02-02',13000000);
insert into compte(id_operation,id_type_compte,id_agence,id_client,numero,date_creation,solde)values(2,3,3,2,125125,'2017-02-02',14000000);
insert into compte(id_operation,id_type_compte,id_agence,id_client,numero,date_creation,solde)values(3,1,4,3,125125,'2017-02-02',12000000);
insert into compte(id_operation,id_type_compte,id_agence,id_client,numero,date_creation,solde)values(4,2,5,4,125125,'2017-02-02',16000000);

insert into agence(nom,id_ville,id_banque)values('Tanjombato',7,3);
insert into agence(nom,id_ville,id_banque)values('Analakely',1,1);
insert into agence(nom,id_ville,id_banque)values('Fenoarivo',3,8);
insert into agence(nom,id_ville,id_banque)values('Andravohangy',9,10);
insert into agence(nom,id_ville,id_banque)values('Andoharanofotsy',10,5);
insert into agence(nom,id_ville,id_banque)values('Ankadimbahoaka',2,3);
insert into agence(nom,id_ville,id_banque)values('Anosizato',4,4);
insert into agence(nom,id_ville,id_banque)values('Tsampanana',5,1);
insert into agence(nom,id_ville,id_banque)values('Antaninarenina',6,10);